### ISSUE TITLE
how to restore my original open psid

### ISSUE THREAD

**Issue by Croden1999** [TeamFAPS/CEX2DEX#2]
![IMG_20220914_180017_1](https://user-images.githubusercontent.com/61804715/191161331-a35fd9a6-dbf2-4c94-885e-3876cbe9cc3e.jpg)
i have original open psid, but i did not knew how to restore it, and also i could not activate my psn (here is display C0-9255-1 error occurred). plz tell me how to restore the original open psid, thx.

**Comment by Princess-of-Sleeping** [comment]
You can preferentially install them by creating a file on the memory card. The file is binary.

https://github.com/TeamFAPS/CEX2DEX/blob/a40b36c13dcf0c32d24dfcd3218631e122febf32/CEX2DEX-Kernel/src/main.c#L319-L335

**Comment by Croden1999** [comment]
> You can preferentially install them by creating a file on the memory card. The file is binary.
> 
> https://github.com/TeamFAPS/CEX2DEX/blob/a40b36c13dcf0c32d24dfcd3218631e122febf32/CEX2DEX-Kernel/src/main.c#L319-L335

thx so much, sir, i try it now. XD

**Comment by Croden1999** [comment]
thx so much again, Mr. @Princess-of-Sleeping, here is restored and activate my psn.
